{
  "openapi": "3.0.1",
  "info": {
    "title": "API V1",
    "version": "v1"
  },
  "paths": {
    "/api/v1/devices": {
      "post": {
        "summary": "Creates a device",
        "tags": [
          "Devices"
        ],
        "security": [
          {
            "api_key": [

            ]
          }
        ],
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "device created",
            "content": {
            }
          },
          "422": {
            "description": "invalid request",
            "content": {
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "serial_number": {
                    "type": "string"
                  },
                  "firmware_version": {
                    "type": "string"
                  },
                  "registered_on": {
                    "type": "string",
                    "format": "date"
                  }
                },
                "required": [
                  "serial_number",
                  "firmware_version",
                  "registered_on"
                ]
              }
            }
          }
        }
      }
    },
    "/api/v1/devices/{id}": {
      "get": {
        "summary": "Retrieves a device",
        "tags": [
          "Devices"
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "security": [
          {
            "api_key": [

            ]
          }
        ],
        "responses": {
          "200": {
            "description": "name found",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    }
                  },
                  "required": [
                    "id"
                  ]
                }
              }
            }
          },
          "404": {
            "description": "device not found",
            "content": {
            }
          }
        }
      }
    },
    "/api/v1/readings": {
      "post": {
        "summary": "Creates a reading",
        "tags": [
          "Readings"
        ],
        "security": [
          {
            "api_key": [

            ]
          }
        ],
        "parameters": [

        ],
        "responses": {
          "201": {
            "description": "reading created",
            "content": {
            }
          },
          "422": {
            "description": "invalid request",
            "content": {
            }
          }
        },
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "device_id": {
                    "type": "integer"
                  },
                  "temperature": {
                    "type": "number"
                  },
                  "humidity": {
                    "type": "number"
                  },
                  "carbon_monoxide": {
                    "type": "integer"
                  },
                  "health_status": {
                    "type": "string",
                    "maxLength": 150
                  },
                  "reading_at": {
                    "type": "string",
                    "format": "date-time"
                  }
                },
                "required": [
                  "temperature"
                ]
              }
            }
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "{url}",
      "variables": {
        "url": {
          "enum": [
            "https://ac.alkema.ca",
            "http://localhost:3000"
          ],
          "default": "https://ac.alkema.ca"
        }
      }
    }
  ],
  "components": {
    "securitySchemes": {
      "api_key": {
        "type": "apiKey",
        "in": "header",
        "name": "X-API-KEY"
      }
    }
  }
}